import Aircraft from "./Aircraft.svg";
import Airports from "./Airports.svg";
import InternationalCities from "./InternationalCities.svg";
import Routes_DistanceCalculator from "./Routes_DistanceCalculator.svg";
import UsCanadaCities from "./UsCanadaCities.svg";
import OnDemandCharter from "./onDemandCharter.svg";
import ProvenSafetyRecords from "./provenSafetyRecords.svg";
import Reliability from "./reliability.svg";
import Transparency from "./transparency.svg";
import Testimonials from "./testimonials.svg";
import GroupCharter from "./groupCharter.svg";
import AirAmbulance from "./airAmbulance.svg";
import Helicopter from "./helicopter.svg";
import EmptyLeg from "./emptyLeg.svg";
import IndustrySpecific from "./industrySpecific.svg";
import OurOfficesSvg from "./ourOffices.svg";
import RequestQuote from "./requestQuote.svg";
import ReceiveCharterProposal from "./receiveCharterProposal.svg";
import ConfirmAircraft from "./confirmAircraft.svg";
import ReceiveFlightBrief from "./receiveFlightBrief.svg";
import CostCalculator from "./costCalculator.svg";
import FlightTracker from "./flightTracker.svg";
import SafetyFirst from "./safetyFirst.svg";
import TailoredLuxury from "./tailoredLuxury.svg";
import Facebook from './facebook.svg';
import Linkedin from './Linkedin.svg';
import Twitter from './Twitter.svg';
import TimeEfficient from './time-efficinet.svg';
import Productivity from './productivity.svg';
import TravelSoltution from './travelSolution.svg';
import Diamond from './diamond.svg';
import Privacy from './privacy.svg';
import  Accessibility  from './accessbility.svg';
import Shuffle from './shuffle.svg';
import Airplane from './Airplane.svg';
import Terminal from './terminal.svg';
import Broker from './Broker.svg';
import Charter from './Charter.svg';
import Price from './price.svg';
import Service from './Service.svg';
import Search from './search.svg';
import Close from './close-icon.svg';
import Tools from './tools.svg';
import Target from './target.svg';
import Box from './box2.svg';
import Dietry from './Dietry.svg';

export { Aircraft, Airports, InternationalCities, Routes_DistanceCalculator, UsCanadaCities };
export { OnDemandCharter, ProvenSafetyRecords, Reliability, Transparency, Testimonials };
export { GroupCharter, AirAmbulance, Helicopter, EmptyLeg, IndustrySpecific };
export { OurOfficesSvg };
export { RequestQuote, ReceiveCharterProposal, ConfirmAircraft, ReceiveFlightBrief };
export { CostCalculator, FlightTracker, Search };
export { SafetyFirst, TailoredLuxury, Facebook, Linkedin,Twitter };
export { TimeEfficient, Productivity, TravelSoltution, Diamond, Privacy, Accessibility, Shuffle };
export { Airplane, Terminal, Broker, Charter, Price, Service, Tools, Target , Box, Dietry, Close}
